// export default [
//   {
//     language: 'clojure',
//     scopeName: 'source.clojure',
//     path: './clojure.tmLanguage.json',
//     configuration: './clojure.tmLanguage.json',
//   },
//   {
//     language: 'coffeescript',
//     scopeName: 'source.coffee',
//     path: './coffeescript.tmLanguage.json',
//     configuration: './coffeescript.tmLanguage.json',
//   },
//   {
//     language: 'c',
//     scopeName: 'source.c',
//     path: './cpp.tmLanguage.json',
//     configuration: './cpp.tmLanguage.json',
//   },
//   {
//     language: 'cpp',
//     scopeName: 'source.cpp.embedded.macro',
//     path: './cpp.tmLanguage.json',
//     configuration: './cpp.tmLanguage.json',
//   },
//   {
//     language: 'cpp',
//     scopeName: 'source.cpp',
//     path: './cpp.tmLanguage.json',
//     configuration: './cpp.tmLanguage.json',
//   },
//   {
//     language: 'cpp',
//     scopeName: 'source.c.platform',
//     path: './cpp.tmLanguage.json',
//     configuration: './cpp.tmLanguage.json',
//   },
//   {
//     language: 'cpp',
//     scopeName: 'source.cuda-cpp',
//     path: './cpp.tmLanguage.json',
//     configuration: './cpp.tmLanguage.json',
//   },
//   {
//     language: 'csharp',
//     scopeName: 'source.cs',
//     path: './csharp.tmLanguage.json',
//     configuration: './csharp.tmLanguage.json',
//   },
//   {
//     language: 'css',
//     scopeName: 'source.css',
//     path: './css.tmLanguage.json',
//     configuration: './css.tmLanguage.json',
//   },
//   {
//     language: 'dart',
//     scopeName: 'source.dart',
//     path: './dart.tmLanguage.json',
//     configuration: './dart.tmLanguage.json',
//   },
//   {
//     language: 'fsharp',
//     scopeName: 'source.fsharp',
//     path: './fsharp.tmLanguage.json',
//     configuration: './fsharp.tmLanguage.json',
//   },
//   {
//     language: 'go',
//     scopeName: 'source.go',
//     path: './go.tmLanguage.json',
//     configuration: './go.tmLanguage.json',
//   },
//   {
//     language: 'groovy',
//     scopeName: 'source.groovy',
//     path: './groovy.tmLanguage.json',
//     configuration: './groovy.tmLanguage.json',
//   },
//   {
//     language: 'html',
//     scopeName: 'text.html.basic',
//     path: './html.tmLanguage.json',
//     configuration: './html.tmLanguage.json',
//   },
//   {
//     language: 'html',
//     scopeName: 'text.html.derivative',
//     path: './html.tmLanguage.json',
//     configuration: './html.tmLanguage.json',
//   },
//   {
//     language: 'java',
//     scopeName: 'source.java',
//     path: './java.tmLanguage.json',
//     configuration: './java.tmLanguage.json',
//   },
//   {
//     language: 'javascriptreact',
//     scopeName: 'source.js.jsx',
//     path: './javascript.tmLanguage.json',
//     configuration: './javascript.tmLanguage.json',
//   },
//   {
//     language: 'javascript',
//     scopeName: 'source.js',
//     path: './javascript.tmLanguage.json',
//     configuration: './javascript.tmLanguage.json',
//   },
//   {
//     language: 'javascript',
//     scopeName: 'source.js.regexp',
//     path: './javascript.tmLanguage.json',
//     configuration: './javascript.tmLanguage.json',
//   },
//   {
//     language: 'json',
//     scopeName: 'source.json',
//     path: './json.tmLanguage.json',
//     configuration: './json.tmLanguage.json',
//   },
//   {
//     language: 'jsonc',
//     scopeName: 'source.json.comments',
//     path: './json.tmLanguage.json',
//     configuration: './json.tmLanguage.json',
//   },
//   {
//     language: 'jsonl',
//     scopeName: 'source.json.lines',
//     path: './json.tmLanguage.json',
//     configuration: './json.tmLanguage.json',
//   },
//   {
//     language: 'snippets',
//     scopeName: 'source.json.comments.snippets',
//     path: './json.tmLanguage.json',
//     configuration: './json.tmLanguage.json',
//   },
//   {
//     language: 'julia',
//     scopeName: 'source.julia',
//     path: './julia.tmLanguage.json',
//     configuration: './julia.tmLanguage.json',
//   },
//   {
//     language: 'less',
//     scopeName: 'source.css.less',
//     path: './less.tmLanguage.json',
//     configuration: './less.tmLanguage.json',
//   },
//   {
//     language: 'lua',
//     scopeName: 'source.lua',
//     path: './lua.tmLanguage.json',
//     configuration: './lua.tmLanguage.json',
//   },
//   {
//     language: 'perl',
//     scopeName: 'source.perl',
//     path: './perl.tmLanguage.json',
//     configuration: './perl.tmLanguage.json',
//   },
//   {
//     language: 'perl6',
//     scopeName: 'source.perl.6',
//     path: './perl.tmLanguage.json',
//     configuration: './perl.tmLanguage.json',
//   },
//   {
//     language: 'php',
//     scopeName: 'source.php',
//     path: './php.tmLanguage.json',
//     configuration: './php.tmLanguage.json',
//   },
//   {
//     language: 'php',
//     scopeName: 'text.html.php',
//     path: './php.tmLanguage.json',
//     configuration: './php.tmLanguage.json',
//   },
//   {
//     language: 'powershell',
//     scopeName: 'source.powershell',
//     path: './powershell.tmLanguage.json',
//     configuration: './powershell.tmLanguage.json',
//   },
//   {
//     language: 'jade',
//     scopeName: 'text.pug',
//     path: './pug.tmLanguage.json',
//     configuration: './pug.tmLanguage.json',
//   },
//   {
//     language: 'python',
//     scopeName: 'source.python',
//     path: './python.tmLanguage.json',
//     configuration: './python.tmLanguage.json',
//   },
//   {
//     language: 'python',
//     scopeName: 'source.regexp.python',
//     path: './python.tmLanguage.json',
//     configuration: './python.tmLanguage.json',
//   },
//   {
//     language: 'r',
//     scopeName: 'source.r',
//     path: './r.tmLanguage.json',
//     configuration: './r.tmLanguage.json',
//   },
//   {
//     language: 'ruby',
//     scopeName: 'source.ruby',
//     path: './ruby.tmLanguage.json',
//     configuration: './ruby.tmLanguage.json',
//   },
//   {
//     language: 'rust',
//     scopeName: 'source.rust',
//     path: './rust.tmLanguage.json',
//     configuration: './rust.tmLanguage.json',
//   },
//   {
//     language: 'scss',
//     scopeName: 'source.css.scss',
//     path: './scss.tmLanguage.json',
//     configuration: './scss.tmLanguage.json',
//   },
//   {
//     language: 'scss',
//     scopeName: 'source.sassdoc',
//     path: './scss.tmLanguage.json',
//     configuration: './scss.tmLanguage.json',
//   },
//   {
//     language: 'shaderlab',
//     scopeName: 'source.shaderlab',
//     path: './shaderlab.tmLanguage.json',
//     configuration: './shaderlab.tmLanguage.json',
//   },
//   {
//     language: 'shellscript',
//     scopeName: 'source.shell',
//     path: './shellscript.tmLanguage.json',
//     configuration: './shellscript.tmLanguage.json',
//   },
//   {
//     language: 'sql',
//     scopeName: 'source.sql',
//     path: './sql.tmLanguage.json',
//     configuration: './sql.tmLanguage.json',
//   },
//   {
//     language: 'swift',
//     scopeName: 'source.swift',
//     path: './swift.tmLanguage.json',
//     configuration: './swift.tmLanguage.json',
//   },
//   {
//     language: 'typescript',
//     scopeName: 'source.ts',
//     path: './typescript-basics.tmLanguage.json',
//     configuration: './typescript-basics.tmLanguage.json',
//   },
//   {
//     language: 'typescriptreact',
//     scopeName: 'source.tsx',
//     path: './typescript-basics.tmLanguage.json',
//     configuration: './typescript-basics.tmLanguage.json',
//   },
//   {
//     language: 'typescript',
//     scopeName: 'documentation.injection.ts',
//     path: './typescript-basics.tmLanguage.json',
//     configuration: './typescript-basics.tmLanguage.json',
//   },
//   {
//     language: 'typescript',
//     scopeName: 'documentation.injection.js.jsx',
//     path: './typescript-basics.tmLanguage.json',
//     configuration: './typescript-basics.tmLanguage.json',
//   },
//   {
//     language: 'vb',
//     scopeName: 'source.asp.vb.net',
//     path: './vb.tmLanguage.json',
//     configuration: './vb.tmLanguage.json',
//   },
//   {
//     language: 'xml',
//     scopeName: 'text.xml',
//     path: './xml.tmLanguage.json',
//     configuration: './xml.tmLanguage.json',
//   },
//   {
//     language: 'xsl',
//     scopeName: 'text.xml.xsl',
//     path: './xml.tmLanguage.json',
//     configuration: './xml.tmLanguage.json',
//   },
//   {
//     language: 'dockercompose',
//     scopeName: 'source.yaml',
//     path: './yaml.tmLanguage.json',
//     configuration: './yaml.tmLanguage.json',
//   },
//   {
//     language: 'yaml',
//     scopeName: 'source.yaml',
//     path: './yaml.tmLanguage.json',
//     configuration: './yaml.tmLanguage.json',
//   },
// ]

export default [
  {
    language: 'java',
    scopeName: 'source.java',
    path: './java.tmLanguage.json',
    configuration: './java.tmLanguage.json',
  },
  {
    language: 'javascript',
    scopeName: 'source.js',
    path: './javascript.tmLanguage.json',
  },
]
